# Use root/example as user/password credentials

services:

  backend:
    container_name: backend
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - SECRET_KEY=test123

  mongo:
    image: mongo
    restart: always
    volumes:
      - mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: task_manager

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_DATABASE: task_manager
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017
      ME_CONFIG_BASICAUTH: false
volumes:
  mongodb: