const {
    ROLES, GLOBAL_ROLES, ENTITIES, ACTION_TYPES
} = require('../constants');
const { CREATE, READ, UPDATE, DELETE } = ACTION_TYPES;

const permissionUtil = {
    [GLOBAL_ROLES.SUPER_ADMIN]: {
        [ENTITIES.PROJECT_USER]: [CREATE, READ, UPDATE, DELETE],
        [ENTITIES.COMPANY]: [CREATE, READ, UPDATE, DELETE],
        [ENTITIES.PROJECT]: [CREATE, READ, UPDATE, DELETE],
        [ENTITIES.TASK]: [CREATE, READ, UPDATE, DELETE],
        [ENTITIES.TASK_COMMENT]: [CREATE, READ, UPDATE, DELETE],
        [ENTITIES.ROLE]: [CREATE, READ, UPDATE, DELETE],
    },
    [GLOBAL_ROLES.COMPANY_ADMIN]: {
        [ENTITIES.PROJECT_USER]: [CREATE, READ, UPDATE, DELETE],
        [ENTITIES.COMPANY]: [READ, UPDATE],
        [ENTITIES.PROJECT]: [CREATE, READ, UPDATE, DELETE],
        [ENTITIES.TASK]: [CREATE, READ, UPDATE, DELETE],
        [ENTITIES.TASK_COMMENT]: [CREATE, READ, UPDATE, DELETE],
        [ENTITIES.ROLE]: [READ],
    },
    [ROLES.PROJECT_ADMIN]: {
        [ENTITIES.PROJECT_USER]: [CREATE, READ, UPDATE, DELETE],
        [ENTITIES.COMPANY]: [READ],
        [ENTITIES.PROJECT]: [READ, UPDATE, DELETE],
        [ENTITIES.TASK]: [CREATE, READ, UPDATE, DELETE],
        [ENTITIES.TASK_COMMENT]: [CREATE, READ, UPDATE, DELETE],
        [ENTITIES.ROLE]: [READ],
    },
};

module.exports = permissionUtil;
