apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresdb-deployment
  labels:
    app: postgresdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresdb
  template:
    metadata:
      labels:
        app: postgresdb
    spec:
      containers:
        - name: postgresdb
          image: postgres:16-alpine
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: POSTGRES_DB
              value: "task_manager"
            - name: DB_HOST
              value: "db"
            - name: DB_PORT
              value: "5432"
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data

---
apiVersion: v1
kind: Service
metadata:
  name: postgresdb-service
spec:
  type: LoadBalancer
  selector:
    app: postgresdb
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
